odiseo_conagra_frontend_conagra_latam_page:
    path:     /conagra-latam
    defaults: { _controller: OdiseoConAgraBundle:Frontend/ConagraLatam:showLatamPage }
    
odiseo_conagra_frontend_conagra_latam_country_information:
    path:    /country
    defaults: { _controller: OdiseoConAgraBundle:Frontend/ConagraLatam:showMap}