parameters:
    odiseo_project.model.user: Odiseo\Bundle\ConAgraBundle\Entity\User
    odiseo_project.repository.user: Odiseo\Bundle\ProjectBundle\Repository\UserRepository
    
    odiseo_backend.homepage_route: odiseo_conagra_backend_dashboard