odiseo_conagra:
    resource: "@OdiseoConAgraBundle/Resources/config/main.yml"
    prefix:   /
    
fos_user_registration_confirmed:
    path:    /register/confirmed
    defaults: { _controller: OdiseoConAgraBundle:Frontend/Intro:index }