odiseo_conagra:
    resource: "@OdiseoConAgraBundle/Resources/config/routing/main.yml"
    prefix:   /
    
fos_user_registration_confirmed:
    pattern: /register/confirmed
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: odiseo_conangra_frontend_welcome
        permanent: true