services:
#    odiseo_conangra.example:
#        class: Odiseo\Bundle\ConAngraBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    conagra_user.registration.form.type:
        class: Odiseo\Bundle\ConAgraBundle\Form\Type\RegistrationFormType
        arguments: [@translator , %fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: conagra_user_registration }
            
    conagra_user.form.handler.registration:
        class: Odiseo\Bundle\ConAgraBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator"]
        scope: request
        public: false
        
    conagra.twig.extension.route_utils:
        class: Odiseo\Bundle\ConAgraBundle\Twig\RouteUtilsExtension
        arguments: ["@request_stack"]
        tags:
            - { name: twig.extension }
            
    conagra.backend.menu_builder:
        class: Odiseo\Bundle\ConAgraBundle\Menu\BackendMenuBuilder
        arguments: ["@knp_menu.factory", "@security.context"]
        
    conagra.backend.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: conagra.backend.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: backend_main_menu } # The alias is what is used to retrieve the menu

    translation.loader.db:
        class: Odiseo\Bundle\ConAgraBundle\Services\DbPhrasesLoader
        arguments: [@doctrine.orm.entity_manager]
        tags:
           - { name: translation.loader, alias: db}     

