odiseo_conagra_backend_distributor_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: odiseo_conagra.controller.distributor:indexAction
        _sylius:
            template: OdiseoConAgraBundle:Backend/Distributor:index.html.twig
            paginate: 100
            
odiseo_conagra_backend_distributor_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: odiseo_conagra.controller.distributor:createAction
        _sylius:
            template: OdiseoConAgraBundle:Backend/Distributor:create.html.twig
            redirect: odiseo_conagra_backend_distributor_index

odiseo_conagra_backend_distributor_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: odiseo_conagra.controller.distributor:updateAction
        _sylius:
            template: OdiseoConAgraBundle:Backend/Distributor:update.html.twig
            redirect: odiseo_conagra_backend_distributor_index

odiseo_conagra_backend_distributor_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: odiseo_conagra.controller.distributor:deleteAction
        _sylius:
            redirect: odiseo_conagra_backend_distributor_index