#Odiseo Backend Routes
odiseo_backend:
    resource: "@OdiseoBackendBundle/Resources/config/routing/main.yml"
    prefix:   /
    
odiseo_conagra_backend_dashboard:
    pattern: /dashboard
    defaults: { _controller: "OdiseoConAgraBundle:Backend/Main:dashboard" }
    
lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /translations

odiseo_conagra_backend_translations:
    pattern: /translations/grid