odiseo_conagra_backend_user_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: odiseo_conagra.controller.user:indexAction
        _sylius:
            template: OdiseoConAgraBundle:Backend/User:index.html.twig
            paginate: 100
            
odiseo_conagra_backend_user_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: odiseo_conagra.controller.user:createAction
        _sylius:
            template: OdiseoConAgraBundle:Backend/User:create.html.twig
            redirect: odiseo_conagra_backend_user_update

odiseo_conagra_backend_user_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: odiseo_conagra.controller.user:updateAction
        _sylius:
            template: OdiseoConAgraBundle:Backend/User:update.html.twig
            redirect: odiseo_conagra_backend_user_update

odiseo_conagra_backend_user_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: odiseo_conagra.controller.user:deleteAction
        _sylius:
            redirect: odiseo_conagra_backend_user_index