Odiseo\Bundle\ConAgraBundle\Entity\Country:
    type: entity
    table: country
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update  
        name:
            column: name
            type: string
            length: 255
        isoCode:
            column: iso_code
            type: string
            length: 2
