Odiseo\Bundle\ConAgraBundle\Entity\Distributor:
    type: entity
    table: distributor
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update  
        name:
            column: name
            type: string
            length: 255
    manyToOne:
        country:
          targetEntity: Odiseo\Bundle\ConAgraBundle\Entity\Country
          joinColumn:
              name: country_id
              referencedColumnName: id
