Odiseo\Bundle\ConAgraBundle\Entity\Language:
    repositoryClass: Odiseo\Bundle\ConAgraBundle\Repository\LanguageRepository
    type: entity
    table: language
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
       locale:
            column: locale
            type: string
            length: 200
       name:
            column: name
            type: string
            length: 200