Odiseo\Bundle\ConAgraBundle\Entity\TriviaQuestion:
    type: entity
    table: trivia_question
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update  
        title:
            column: title
            type: string
            length: 255
        position:
            type: integer
            gedmo:
                - sortablePosition
        country:
            column: country
            type: string
            length: 255
            nullable: true
    oneToMany:
        answers:
          targetEntity: Odiseo\Bundle\ConAgraBundle\Entity\TriviaAnswer
          mappedBy: answer
