Odiseo\Bundle\ConAgraBundle\Entity\TriviaAnswer:
    type: entity
    table: trivia_answer
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update  
        title:
            column: title
            type: string
            length: 255
    manyToOne:
        question:
          targetEntity: Odiseo\Bundle\ConAgraBundle\Entity\TriviaQuestion
          inversedBy: answers
          joinColumn:
              name: question_id
              referencedColumnName: id
