Odiseo\Bundle\ConAgraBundle\Entity\User:
    type: entity
    table: fos_user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update
        fullName:
            column: full_name
            type: string
            length: 255
            nullable: true  
        position:
            column: position
            type: string
            length: 255
            nullable: true
        phone:
            column: phone
            type: string
            length: 255
            nullable: true
    manyToOne:
        country:
          targetEntity: Odiseo\Bundle\ConAgraBundle\Entity\Country
          joinColumn:
              name: country_id
              referencedColumnName: id
        distributor:
          targetEntity: Odiseo\Bundle\ConAgraBundle\Entity\Distributor
          joinColumn:
              name: distributor_id
              referencedColumnName: id